[project]
name = "naive-poem-rev"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.3.2",
    "flagembedding>=1.3.4",
    "openai>=1.65.1",
    "peft>=0.14.0",
    "pymilvus[model]>=2.5.4",
    "torch>=2.6.0",
]
